# Generated by Django 4.2.1 on 2023-05-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('product_image', models.ImageField(upload_to='imagess')),
                ('description', models.CharField(max_length=1000)),
                ('quntity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
